apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: carrier-opt
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - clickhouse-init.yaml
  - clickhouse.yaml
